#!/bin/sh
touch tmp/restart.txt
echo "restarting Passenger app"

echo "restarting Screen running discord bot"
screen -X -S "ch6mans" stuff "^C"
screen -S "ch6mans" -dm bin/rails runner Discord::Bot.new.run
